language: cpp
sudo: required
dist: trusty
branches:
  only:
    - master

matrix:
  include:
    - os: osx
      compiler: clang
      env: CONFIGURATION=Release
      osx_image: xcode7.1

    - os: linux
      compiler: clang
      env: CONFIGURATION=Release

    - os: linux
      compiler: clang
      env: CONFIGURATION=Formatting

before_install:
  # Install packages
  - |
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      brew update
      brew install cmake ninja
    fi

  - |
    if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      sudo dpkg --add-architecture i386
      wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
      echo deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.8 main | sudo tee --append /etc/apt/sources.list
      sudo apt-get update
      sudo apt-get install cmake cmake-data gcc clang-3.8 clang-format-3.8
    fi

install:
  - git submodule update --init --recursive

script:
  - |
    if [ "$CONFIGURATION" = "Formatting" ]; then
      # TODO: Indentation check
    else
      rm -rf build
      mkdir build
      (cd build ; \
        cmake -G Ninja -D CMAKE_BUILD_TYPE=$CONFIGURATION .. && \
        cmake --build . && \
        echo "Running 32-bit tests" && \
        ./test/mrswatsontest -r ../vendor/AudioTestData -m ./main/mrswatson && \
        echo "Running 64-bit tests" && \
        ./test/mrswatsontest64 -r ../vendor/AudioTestData -m ./main/mrswatson64 && \
        echo
      )
    fi
