cmake_minimum_required(VERSION 3.0)

function(configure_target target_NAME target_BITNESS)
  if(${CMAKE_SYSTEM_NAME} MATCHES "Linux")
    if(${target_BITNESS} EQUAL 32)
      set_target_properties(${target_NAME} PROPERTIES COMPILE_FLAGS "-m32 -std=c99")
      set_target_properties(${target_NAME} PROPERTIES LINK_FLAGS "-m32")
    else()
      set_target_properties(${target_NAME} PROPERTIES COMPILE_FLAGS "-m64 -std=c99")
      set_target_properties(${target_NAME} PROPERTIES LINK_FLAGS "-m64")
    endif()
    target_link_libraries(${target_NAME} dl)
  elseif(APPLE)
    if(${target_BITNESS} EQUAL 32)
      set_target_properties(${target_NAME} PROPERTIES OSX_ARCHITECTURES "i386")
    else()
      set_target_properties(${target_NAME} PROPERTIES OSX_ARCHITECTURES "x86_64")
    endif()
  elseif(MSVC)
    if(${target_BITNESS} EQUAL 32)
      set_target_properties(${target_NAME} PROPERTIES COMPILE_FLAGS "/DWIN32=1")
    else()
      set_target_properties(${target_NAME} PROPERTIES COMPILE_FLAGS "/DWIN64=1")
    endif()
  endif()
endfunction()
